//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomWorkWithCustomers
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableModul
    {
        public string Id_do_not_use { get; set; }
        public string Access_Code { get; set; }
        public string Available_Modul { get; set; }
    }
}
