//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomWorkWithCustomers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kinds_of_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kinds_of_service()
        {
            this.TypesOfServices = new HashSet<TypesOfService>();
        }
    
        public int Id { get; set; }
        public string Kind_of_service { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypesOfService> TypesOfServices { get; set; }
    }
}
