//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomWorkWithCustomers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesOfService
    {
        public int Id { get; set; }
        public Nullable<int> KindOfServiceId { get; set; }
        public string TypeOfService { get; set; }
    
        public virtual Kinds_of_service Kinds_of_service { get; set; }
    }
}
