//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomWorkWithCustomers
{
    using System;
    using System.Collections.Generic;
    using PropertyChanged;
    [AddINotifyPropertyChangedInterface]
    public partial class Заявки
    {
        public int Id { get; set; }
        public string Номер_заявки { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public string Вид_услуги { get; set; }
        public string Тип_услуги { get; set; }
        public string Статус { get; set; }
        public string Тип_оборудования { get; set; }
        public string Описание_проблемы { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public string Тип_проблемы { get; set; }
        public string Номер_абонента { get; set; }
    
        public virtual Абоненты Абоненты { get; set; }
    }
}
