//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NevaTelecomAuthorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абоненты
    {
        public string Номер_абонента { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Номер_телефона { get; set; }
        public string Электронная_почта { get; set; }
        public string Адрес_прописки { get; set; }
        public string Адрес_проживания { get; set; }
        public string Серия_и_номер_паспорта { get; set; }
        public string Код_подразделения { get; set; }
        public string Кем_выдан { get; set; }
        public Nullable<System.DateTime> Дата_выдачи_паспорта { get; set; }
        public string Номер_договора { get; set; }
        public Nullable<System.DateTime> Дата_заключения_договора { get; set; }
        public string Тип_договора { get; set; }
        public string Причина_расторжения_договора { get; set; }
        public string Лицевой_счет { get; set; }
        public string Услуги { get; set; }
        public Nullable<System.DateTime> Дата_расторжения_договора { get; set; }
        public string Серийный_номер_оборудования { get; set; }
    }
}
